[package]
name = "pc"
version = "0.1.0"
authors = ["Samuel Walladge <samuel@swalladge.id.au>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
reqwest = "0.9.17"
toml = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
url = "1.7.2"
