# This config is compiled into the binary and is loaded if no config file
# found.

[main]
server = "ubuntu"

[servers.vpaste]
backend = "vpaste"
url = "http://vpaste.net/"

[servers.ots]
backend = "onetimesecret"
url = "https://onetimesecret.com/"

[servers.pip]
backend = "pipfi"
url = "http://p.ip.fi/"


[servers.ubuntu]
backend = "ubuntu"
url = "https://paste.ubuntu.com/"

