[main]
# optional; if missing, will use random server entry
server = "rs"

## optional; if missing, will not log url history.
## if set, will append url of successful pastes to this file, one per line,
## newest to the bottom. The file is created if not existing. Parent directories
## will not be created. If paste successful but failed to write histfile, a
## warning will be printed to stderr and will exit with a non-zero exit code.
# histfile = "/tmp/paste_history.txt"

[servers]

# must be at least one server defined
[servers.vpaste]
backend = "vpaste"
url = "http://vpaste.net/"

[servers.rs]
backend = "generic"
url = "https://paste.rs/"

[servers.haste]
backend = "haste"
url = "https://hastebin.com/"

[servers.termbin]
backend = "fiche"
domain = "termbin.com"
# port is optional; defaults to 9999
port = 9999

[servers.fedora]
backend = "modern_paste"
url = "https://paste.fedoraproject.org/"

[servers.dpastecom]
backend = "dpaste_com"
url = "http://dpaste.com/"
